name             "cookbook-ngxmgdbpy"
maintainer       "Juan Manuel Lopez"
maintainer_email ""
license          "Apache 2.0"
description      "Setup a Nginx - MongoDB - Python environment"
version          "0.0.1"

depends "apt",              "~> 2.5.0"
depends "build-essential",  "~> 2.0.6"
depends "mongodb",          "~> 0.16.1"
depends "nginx",            "~> 2.7.4"
depends "python",           "~> 1.4.6"
depends "runit",            "~> 1.5.10"
depends "smbfs",            "~> 0.4.0"
depends "vim",              "~> 1.1.2"
